# Generated by Django 5.0.dev20230720174544 on 2023-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Эл. почта')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('content', models.TextField(blank=True, verbose_name='Роль')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Персонал',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
